name: Model deploy when pushed to main
on:
  push:
    branches: 
      - main

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Deploy/Update on push to main'
        shell: bash
        
        run: |
          # Install requirements
          pip install -r requirements.txt

          # Pull data & run-cache from S3 and reproduce pipeline
          dvc pull --run-cache
          dvc repro

          # Check if there is a deployment already, if positive update it, otherwise deploys it for the first time
          ./src/scripts/release_pipeline.sh 
